-- AlterTable
ALTER TABLE `Todo` ALTER COLUMN `expiredAt` DROP DEFAULT,
    MODIFY `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `updatedAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);
