version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mysql:
    platform: linux/x86_64
    image: mysql:5.7.38
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: development
      TZ: Asia/Tokyo
    ports:
      - '3307:3306'
volumes:
  mysql_db: