-- DropForeignKey
ALTER TABLE `Todo` DROP FOREIGN KEY `Todo_assignById_fkey`;

-- AlterTable
ALTER TABLE `Todo` MODIFY `createdAt` TIMESTAMP(0) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` TIMESTAMP(0) NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP,
    MODIFY `assignById` INTEGER NULL;

-- AlterTable
ALTER TABLE `User` MODIFY `createdAt` TIMESTAMP(0) NOT NULL DEFAULT NOW(),
    MODIFY `updatedAt` TIMESTAMP(0) NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP;

-- AddForeignKey
ALTER TABLE `Todo` ADD CONSTRAINT `Todo_assignById_fkey` FOREIGN KEY (`assignById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
